[build]
  command = "npm run build-only"
  publish = "dist"

[build.environment]
  # These are client-side environment variables for EmailJS
  # They are safe to expose as they are public keys/IDs
  SECRETS_SCAN_OMIT_KEYS = "VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_TEMPLATE_ID"
  
  # Omit scanning in dist folder since it contains built assets
  SECRETS_SCAN_OMIT_PATHS = "dist/**"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
